---
- name: setup os for k8s
  hosts: all
  remote_user: root
  tasks:

  - name: set hostname
    hostname:
      name: "{{ inventory_hostname }}"

  - name: remove tmpfs from /etc/fstab
    lineinfile:
      path: /etc/fstab
      regexp: '.*swap.*'
      state: absent
    notify:
      - remove_swap

  - name: update rpms
    yum:
      name: '*'
      state: latest
      disablerepo: docker-ce-stable,kubernetes
    notify:
      - os_reboot
      - os_reboot_wait

  - name: disable selinux
    replace:
      dest: /etc/selinux/config
      regexp: '^SELINUX=.*$'
      replace: 'SELINUX=disabled'
    notify:
      - os_reboot
      - os_reboot_wait

  - name: install pre rpms
    yum:
      name:
        - firewalld
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
      state: latest

  - name: start firewalld
    service:
      name: firewalld
      enabled: true
      state: started

  - name: add sysctl file
    copy:
      content: |
        net.bridge.bridge-nf-call-ip6tables = 1
        net.bridge.bridge-nf-call-iptables = 1
        vm.swappiness = 10
      dest: /etc/sysctl.d/k8s.conf
    notify:
      - sysctl_reload

  - name: get docker ce repo
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/

  - name: enable Oracle Linux ol7_addons repo
    ini_file:
      path: /etc/yum.repos.d/public-yum-ol7.repo
      section: ol7_addons
      option: enabled
      value: 1
    when:
      - ansible_distribution == "OracleLinux"

  - name: install docker rpms
    yum:
      name:
        - docker-ce-18.09.6-3.el7.x86_64
        - docker-ce-cli-18.09.6-3.el7.x86_64
        - containerd.io
      state: installed

  - name: start docker
    service:
      name: docker
      enabled: true
      state: started

  - name: add k8s repo file
    copy:
      dest: /etc/yum.repos.d/kubernetes.repo
      content: |
        [kubernetes]
        name=Kubernetes
        baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        enabled=1
        gpgcheck=0

  - name: install k8s rpms
    yum:
      name:
        - kubelet-1.14.2
        - kubeadm-1.14.2
        - kubectl-1.14.2
      state: installed

  - name: open k8s firewall
    firewalld:
      port: "{{ item }}"
      permanent: true
      immediate: true
      state: enabled
    with_items:
      - 6443/tcp
      - 2379-2380/tcp
      - 10250/tcp
      - 10251/tcp
      - 10252/tcp
      - 30000-32767/tcp

  - name: open flannel firewall
    firewalld:
      port: "{{ item }}"
      permanent: true
      immediate: true
      state: enabled
    with_items:
      - 8285/udp
      - 8472/udp

  - name: start docker
    service:
      name: kubelet
      enabled: true

  handlers:
  - name: remove_swap
    command:
      cmd: swapoff -a

  - name: sysctl_reload
    command:
      cmd: sysctl --system

  - name: systemctl_daemon_reload
    command:
      cmd: systemctl daemon-reload

  - name: restart_kubelet
    yum:
      name: kubelet
      state: restarted

  - name: os_reboot
    command:
      cmd: reboot
    async: 1
    poll: 0
    ignore_errors: true

  - name: os_reboot_wait
    wait_for:
      host: "{{ ansible_host }}"
      port: 22
      delay: 15
    delegate_to: localhost

